### ISSUE TITLE
'NoSuchKey' S3 cache errors

### ISSUE THREAD

**Issue by riyadhalnur** [prerender/prerender#296]
Deployed a self hosted version of prerender to Heroku with S3 HTML cache enabled. Whenever I try hitting the server with a URL for it to cache, this is what shows up in the logs.

```
{ [NoSuchKey: The specified key does not exist.] 
Mar 10 00:43:47 webablerender app/web.1:  2016-03-10T08:43:47.233Z got 504 in 817ms for favicon.ico 
Mar 10 00:43:47 webablerender app/web.1:    message: 'The specified key does not exist.', 
Mar 10 00:43:47 webablerender app/web.1:    code: 'NoSuchKey', 
Mar 10 00:43:47 webablerender app/web.1:    region: null, 
Mar 10 00:43:47 webablerender app/web.1:    time: Thu Mar 10 2016 08:43:46 GMT+0000 (UTC), 
Mar 10 00:43:47 webablerender app/web.1:    requestId: '7358796100DAD80A', 
Mar 10 00:43:47 webablerender app/web.1:    extendedRequestId: 'xuIBXUU9Yc+BSBnU/Fi9gvxgsE0fhutWF36mDJ1OPgveH2HW+VI8rqClY2L2ZTHq', 
Mar 10 00:43:47 webablerender app/web.1:    statusCode: 404, 
Mar 10 00:43:47 webablerender app/web.1:    retryable: false, 
Mar 10 00:43:47 webablerender app/web.1:    retryDelay: 65.99937928840518 } 
```

The page does render in the browser but due to it not caching the page, bigger pages time out when debugging a URL with Facebook's Open Graph Debugger.

**Comment by thoop** [comment]
Hmm, can you print out the key and then check S3 to see if it's there? That is expected the first time you access the URL. After it's cached, that should go away.

It looks like that request is for favicon.ico. Your Prerender server shouldn't cache your favicon.ico so that might be why that one fails. You might want to block that request at the middleware level.

**Comment by riyadhalnur** [comment]
The key exists because the same key is being used to upload files to S3. 

Even though the request is for the favicon, I don't see any HTML files being saved to S3.

**Comment by thoop** [comment]
Hmm, so the files aren't being saved to S3 in the first place? Are there any errors from that call when trying to save those to S3?

**Comment by riyadhalnur** [comment]
This is the full error stack

```
{ [NoSuchKey: The specified key does not exist.] 
Mar 10 01:05:05 webablerender app/web.1:    message: 'The specified key does not exist.', 
Mar 10 01:05:05 webablerender app/web.1:    code: 'NoSuchKey', 
Mar 10 01:05:05 webablerender app/web.1:    region: null, 
Mar 10 01:05:05 webablerender app/web.1:    time: Thu Mar 10 2016 09:05:04 GMT+0000 (UTC), 
Mar 10 01:05:05 webablerender app/web.1:    requestId: 'A81F801D807AFD', 
Mar 10 01:05:05 webablerender app/web.1:    extendedRequestId: '8lz60uBlzj359O9fdYDgr9Y/TgoDmY3lrQp5O+Xpugzckj4KXIxEvQhhcyH', 
Mar 10 01:05:05 webablerender app/web.1:    statusCode: 404, 
Mar 10 01:05:05 webablerender app/web.1:    retryable: false, 
Mar 10 01:05:05 webablerender app/web.1:    retryDelay: 39.57472927868366 } 
```

**Comment by thoop** [comment]
That looks like the error from the call to `this.cache.get`, right? That should cause the page to be rendered on the fly and then saved to S3 through this call: `this.cache.set`. Does `this.cache.set` actually enter the HTML into S3?

**Comment by riyadhalnur** [comment]
I'll check and get back to you.

**Comment by rubenjimenez** [comment]
Hi,

I'm suffering the same, but in my case there're even some pages that don't render properly. I just get a blank page when I try to access using "?_escaped_fragment_=".

`{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Mon Mar 14 2016 13:12:01 GMT+0000 (UTC),
  requestId: '2F40D27C795C0579',
  extendedRequestId: 'cEPc7d05fAem9mqPG/JGpPU+gcfauk0VgJxPYY0zVXdE0KeWUEuXonm638/HeRzOMTIUeBcVO+E=',
  statusCode: 404,
  retryable: false,
  retryDelay: 1.1503562796860933 }`

**Comment by thoop** [comment]
Can you send me the URL you are seeing this on? I'd love to look into it. todd@prerender.io

**Comment by laurent-le-graverend** [comment]
Same situation here @thoop ; I debugged a little bit.

`afterPhantomRequest` in the S3 plugin is never reached.

`this._pluginEvent("afterPhantomRequest"` does not reaches the callback in server.js.

Maybe an issue referencing the s3 plugin event?

I am using a basic configuration:
```
server.use(prerender.sendPrerenderHeader());
// server.use(prerender.basicAuth());
server.use(prerender.whitelist());
// server.use(prerender.blacklist());
// server.use(prerender.logger());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
// server.use(prerender.inMemoryHtmlCache());
server.use(prerender.s3HtmlCache());
```

**Comment by thoop** [comment]
@laurent-le-graverend Can you post your entire Prerender console output when you see that happening? Feel free to remove the URL being accessed if you want to keep that private

**Comment by laurent-le-graverend** [comment]
Sure @thoop !

Here is an example doing two CURLs to something like:
`curl 'https://www.example.com/something?_escaped_fragment_='`

```
$ node server.js
2016-04-02T23:34:53.191Z starting worker thread #0
2016-04-02T23:34:53.198Z starting worker thread #1
2016-04-02T23:34:53.509Z starting phantom...
2016-04-02T23:34:53.516Z Server running on port 3000
2016-04-02T23:34:53.571Z starting phantom...
2016-04-02T23:34:53.576Z Server running on port 3000
2016-04-02T23:34:53.590Z started phantom
2016-04-02T23:34:53.651Z started phantom
2016-04-02T23:34:58.369Z getting https://www.example.com/something
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Sat Apr 02 2016 23:34:58 GMT+0000 (UTC),
  requestId: '4DAAAB0D149BF642',
  extendedRequestId: '3EWDtGo/UbbJjXLZIQsKgxL6lAx+ZKS9qYzkr0nJnqD7xVkcaEuLTk1lh+ibxeTQf4idqJUtsSA=',
  statusCode: 404,
  retryable: false,
  retryDelay: 99.28631708025932 }
2016-04-02T23:35:01.811Z got 200 in 3442ms for https://www.example.com/something
2016-04-02T23:35:35.447Z getting https://www.example.com/something
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Sat Apr 02 2016 23:35:35 GMT+0000 (UTC),
  requestId: 'A5AB4252482662A2',
  extendedRequestId: 'UzLUIC4msdR8k0EGqnGOAW2Qkt118dMDzAO7Wa0sAF8+W/E1aJAUdbW+zykBaqia7DtWSKR4Y34=',
  statusCode: 404,
  retryable: false,
  retryDelay: 22.05928978510201 }
2016-04-02T23:35:39.197Z got 200 in 3750ms for https://www.example.com/something
```

Nothing is being uploaded to my S3 bucket.

**Comment by rubenjimenez** [comment]
After updating the prerender to version 4.0.5 we have detected that the Facebook crawler fails the first time it tries to cache a concrete page.

We have to force Facebook to scrape the page again manually using the debugger (https://developers.facebook.com/tools/debug/). In previous versions, it cached the page automatically at first attempt.

After updating prerender, we also started to see the S3 no such key errors in log. Maybe it is related with S3 caching.

**Comment by riyadhalnur** [comment]
@rubenjimenez I think the acebook problem is related to the fact that it times out if the server takes too long to respond. on successive attempts, it picks up the cached version within the timeout limit. tbh, the open graph debugger sucks big time!

**Comment by Nyoroon** [comment]
same problem
```
2016-04-11T12:56:20.274Z getting http://meow/page/meow <- POST #1
Debug string
get http://meow/meow
2016-04-11T12:56:22.426Z got 200 in 2152ms for http://meow/page/meow
2016-04-11T12:58:46.639Z getting http://meow/page/meow <- POST#2
Debug string
get http://meow/meow
2016-04-11T12:58:53.656Z got 200 in 7017ms for http://meow/page/meow <- GET
2016-04-11T12:59:06.393Z getting http://meow/page/meow
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Mon Apr 11 2016 12:59:06 GMT+0000 (UTC),
  requestId: '65CD505463C754A9',
  extendedRequestId: 'IO7T8GNqnEAZJs98AoxZY5pUbr5KQ6lWeRsiV28diNlPZjJBL5pkviIwo3yoyuHd4HFLnSRzLaU=',
  statusCode: 404,
  retryable: false,
  retryDelay: 66.40352057293057 }
Debug string
get http://meow/meow
2016-04-11T12:59:09.013Z got 200 in 2620ms for http://meow/page/meow
```
config
```
server.use(prerender.sendPrerenderHeader());
// server.use(prerender.basicAuth());
// server.use(prerender.whitelist());
// server.use(prerender.blacklist());
server.use(prerender.logger());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
// server.use(prerender.inMemoryHtmlCache());
server.use(prerender.s3HtmlCache());
```

**Comment by rubenjimenez** [comment]
I updated to the last version, 4.0.7 (I had 4.0.5) and I keep getting the same error.

What I don't understand is why the field "region" is printed as null. Theoretically it is already defined.

**Comment by thoop** [comment]
Yeah that's really weird. Let me look more into this and get back to everyone.

**Comment by nick-zh** [comment]
I suffer from this as well, from time to time i get additional trace with it, maybe this helps.
Not sure if it is related though, since i don get the trace everytime i get the key error.

`/prerender/node_modules/prerender/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: req.prerender.page.get is not a function
    at Object.module.exports.onPhantomPageCreate (/prerender/node_modules/prerender/lib/plugins/raschUseragent.js:17:32)
    at next (/prerender/node_modules/prerender/lib/server.js:57:20)
    at next (/prerender/node_modules/prerender/lib/server.js:59:13)
    at next (/prerender/node_modules/prerender/lib/server.js:59:13)
    at next (/prerender/node_modules/prerender/lib/server.js:59:13)
    at Object.server._pluginEvent (/prerender/node_modules/prerender/lib/server.js:64:5)
    at Object.server.onPhantomPageCreate (/prerender/node_modules/prerender/lib/server.js:228:11)
    at Object.server.createPage (/prerender/node_modules/prerender/lib/server.js:140:14)
    at /prerender/node_modules/prerender/lib/server.js:126:15
    at next (/prerender/node_modules/prerender/lib/server.js:52:28)
`

**Comment by thoop** [comment]
So, when testing this locally I'm seeing this:
```
2016-05-08T19:48:25.006Z getting https://prerender.io/
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Sun May 08 2016 14:48:25 GMT-0500 (CDT),
  requestId: '384371639342EAD6',
  extendedRequestId: 't6c/E09kgcWN3mJ/SR9p92V35lR+iMaW2CRT4Gp2P0Gd+9bg2J/PxR2Wy8D3gY+7BTZ6fvypq3A=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 86.54179975856096 }
2016-05-08T19:48:29.359Z got 200 in 4353ms for https://prerender.io/
2016-05-08T19:48:33.256Z getting https://prerender.io/
cache hit
2016-05-08T19:48:33.549Z got 200 in 293ms for https://prerender.io/
```

The `NoSuchKey` error is fine since that's just saying it couldn't find that page in S3, so the Prerender server then renders it on the fly. It's then saved into the cache where the second request pulls that page out of S3 and shows a cache hit.

The real issue seems to be the fact that some people aren't seeing their pages uploaded to their S3 bucket. @laurent-le-graverend can you ensure that the AWS credentials you are using have the correct IAM roles to be able to upload to your S3 bucket?

**Comment by ngr79** [comment]
@thoop Getting the same problem here - I dont think its an S3 permissions issue, I don't think that the afterPhantomRequest event is firing. If I put a console.log as the very first line in that event it never gets outputted, yet the call to the lib/server.js ~ line 444 is being made. I think that the response is being sent before the event gets to fire.

**Comment by laurent-le-graverend** [comment]
@thoop I tried with AWS full access admin credentials to be sure, the issue is here.

**Comment by ankitkl** [comment]
I'm getting same error and prerender creates empty folder on s3.

Error Snippets:
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Thu May 19 2016 04:13:43 GMT+0000 (UTC),
  requestId: '61D2FAD84EF5B6F4',
  extendedRequestId: 'r5LeTQ0xI5AMxnwwo7QSnHNTpwEIsuq9YDpiU/JGOoVv/OX3zAAS/oAUb13UtIvaBEVi8ppMT1s=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 45.74855896644294 }

**Comment by slu125** [comment]
Not sure if it is the cause, but it seems that once there is an javascript error while interpreting the webpage by phantomjs/prerender, it does not call `afterPhantomRequest` of the s3HtmlCache and therefore does not upload the HTML to S3. However, prerender returns the fully rendered page.

If I try to prerender a page, that would **not** throw a javascript error, then this page gets correctly stored in S3 and a subsequent requests are a hit.

So I assume the issue is not a configuration error (e.g. permissions in AWS)

The error I see in prerender console output is:
`TypeError: undefined is not a function (evaluating 'Object.assign(window,c["default"])')`

I tested this with latest master commit `c8bbe74495ecae583a93f8dee4253bde87047a9c`

**Comment by clintbeacock** [comment]
Same issue is occurring for me.  Downgrading to 4.0.5 worked for me.

**Comment by thoop** [comment]
@slu125 What status code are you seeing returned when there is a javascript error? I'm not able to reproduce that on my end by inserting a JS error onto the page being rendered.

@ngr79 @laurent-le-graverend @ankitkl @clintbeacock Can you try with the change that I just pushed? The change should wait until the document is actually saved in S3 before proceeding in case something weird is happening there.

I'm not able to reproduce any of this locally so if anyone has a URL that I can test this with, please send it to me at todd@prerender.io. Thanks!

**Comment by slu125** [comment]
@thoop thanks for taking the time to investigate this. I am getting status code 200. Tested with the latest changes.

This is the output of prerender when I run `curl http://localhost:3000/https://www.lingoda.com`. curl outputs the rendered page.

```
2016-06-02T13:56:41.232Z getting https://www.lingoda.com/
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Thu Jun 02 2016 13:56:41 GMT+0000 (UTC),
  requestId: 'B16DB2745A07B73E',
  extendedRequestId: 'k8l7MoeX5dVjcjF39gmJGGeaI69Gi3Wu28OxCw27uSkFOjmAAjp5hWvOXutmAQQJDHS9SZwnLtY=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 6.422512023709714 }
TypeError: undefined is not a function (evaluating 'Object.assign(window,c["default"])')

  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/components.f10f35591a89560dfcad.js:12
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in t
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/components.f10f35591a89560dfcad.js:21
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in t
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/components.f10f35591a89560dfcad.js:21
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in t
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/components.f10f35591a89560dfcad.js:18
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in t
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/components.f10f35591a89560dfcad.js:1
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in t
  https://d2vg2ouqaix1b8.cloudfront.net/assets/transitional/transitional_vendor.0924d686ac026514f06f.js:1 in webpackJsonp
2016-06-02T13:56:44.082Z error setting header: [TypeError: The header content contains invalid characters]
2016-06-02T13:56:44.084Z got 200 in 2852ms for https://www.lingoda.com/
```

**Comment by laurent-le-graverend** [comment]
Thanks for helping.

@thoop also getting a 200 now, but still doesn't seams to be able (or try) to upload the rendered cache to S3.

```
2016-06-02T14:44:53.305Z getting https://www.example.com/home
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Thu Jun 02 2016 14:44:53 GMT+0000 (UTC),
  requestId: '0B913C0583F70CC7',
  extendedRequestId: 'FTcoXdbul2QrSfuJ6XPAhg+OOE3r+smtbBzyCP2MPuRMJLKALGn4haETvusEwelAeTe4a1uPAyo=',
  statusCode: 404,
  retryable: false,
  retryDelay: 17.435489501804113 }
2016-06-02T14:45:00.626Z got 200 in 7321ms for https://www.example.com/home
```

**Comment by ngr79** [comment]
@thoop , unfortunately, I too am still seeing the same issue as the others. It does not appear to be attempting to set the cache

**Comment by thoop** [comment]
@laurent-le-graverend or @ngr79 can you email me the URL that you are testing? todd@prerender.io

Or can you put some console logs in https://github.com/prerender/prerender/blob/master/lib/plugins/s3HtmlCache.js#L28 in order to see if that function is being called or if it's calling `this.cache.set`?

I can't reproduce that locally so any other info you can provide there would be super helpful in making sure we get this fixed!

**Comment by alexgandy** [comment]
@thoop This can be resolved by adding `server.use(prerender.s3HtmlCache());` above the other plugins in `server.js`.

If you leave it at the end of the plugins list it never gets applied correctly in [_pluginEvent](https://github.com/prerender/prerender/blob/master/lib/server.js#L45)

If you add around L50 in _pluginEvent:
```
if (methodName === 'afterPhantomRequest') {
  console.log('-----------------------------------------');
  console.log(_this.plugins[index++]);
  console.log('method: ', _this.plugins[index++][methodName]);
  console.log('-----------------------------------------');
}
```

You should see:
```
-----------------------------------------
{ onPhantomPageCreate: [Function] }
method:  undefined
-----------------------------------------
```

Because it seems like index is always zero, it's sort of a hack to force s3HtmlCache to be the first element in the plugins array...

Hope this helps.

**Comment by thoop** [comment]
Thanks @alexgandy!

It looks like you are incrementing `index++` multiple times there, but what you found is correct. From the example URL you sent to my email, it looks like you are adding our prerender-status-code meta tag to the page like:

`<meta name="prerender-status-code" content="200">`

In the httpHeaders module we do a strict match on `200` being an integer when it comes back as a string so that should probably be changed. But since you are setting a status code of 200, `res.send` is being called which skips all the rest of the plugins in the chain. Maybe we should change httpHeaders to do a non-strict check of `statusCode != 200` and also just set `req.prerender.statusCode` to the correct status code before calling `next()` instead of calling `res.send`.

Is everyone else having this issue setting the prerender-status-code header to 200 in their HTML?

**Comment by laurent-le-graverend** [comment]
Yes @thoop ! We also use the pretender status codes in our web application...

**Comment by thoop** [comment]
Awesome. We'll make this change on master soon!

**Comment by thoop** [comment]
Hi all, this issue should be fixed in Prerender v4.1.0. Please reopen if you continue to see issues after upgrading. Thanks!
