### ISSUE TITLE
Error closing Chrome tab: unable to dispose of browser context

### ISSUE THREAD

**Issue by diegojonio** [prerender/prerender#531]
Hi everyone!

I'm getting this message: "error closing Chrome tab unable to dispose of browser context".
I'm not sure if this is an actual error, but I'm noticing that the memory usage is extremely high.

I've a load of 15 request per minute, and each request takes 2.2s to render. 
The memory consumption grows 150mb per hour, and I have the heap configured to --max_old_space_size=12288.

I'm using:
Node: 8.11.3
pm2: 2.10.4
Chrome: 68.0.3440.75 
Ubuntu: 16.04

I haven't seen a out of memory exception with this configuration yet, but the high memory consumption and this message concerns me.

<img width="1485" alt="screen shot 2018-08-03 at 7 39 47 pm" src="https://user-images.githubusercontent.com/2515534/43671778-16477074-9755-11e8-9769-cbfbaffe73c7.png">

**Comment by thoop** [comment]
I wonder if something changed in Chrome 68 that we need to upgrade. I haven't seen this before and 15 requests per minute should be fine. How much RAM is available on your machine?

I see you have --no-sandbox set as a config and we've seen issues with that in the past. Are you using Docker?

**Comment by 87439247** [comment]
I have the same problem both in docker and pc

**Comment by thoop** [comment]
For Docker issues, you might want to give it access to more RAM like in this issue:

https://github.com/prerender/prerender/issues/524

**Comment by 87439247** [comment]
on my pc , not docker , my env is : 
centos 7.5 
node10.8 
chrome 68.0.3440.84

prerender server config is 

var server = prerender({
    pageDoneCheckInterval: 100,
    pageLoadTimeout: 40 * 1000,
    logRequests: true,
    chromeFlags: ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars']

});

prerender alwasy print "2018-08-07T02:34:24.950Z error closing Chrome tab unable to dispose of browser context" every request

the same in docker

**Comment by thoop** [comment]
It looks like this is an issue with Chrome 68. We'll take a look at what changed in 68 to cause this to break.

**Comment by dzydzany** [comment]
In the meantime, looks like restarting prerender every x minutes works, depending on how many crawls at the service you have. I confirm that it happens since Chrome 68, and that Chrome uses a big amount of RAM because of not closing tabs (got up to 20 GB in my case).

**Comment by diegojonio** [comment]
I'm not using docker and the server as 16gb of RAM which 12gb is allocated to prerender. I'm using [memory cache](https://github.com/prerender/prerender-memory-cache) with default config.

**Comment by thoop** [comment]
So this is how we close tabs currently:

https://github.com/prerender/prerender/blob/dd864a6bab41f357f9db4dd048a7c1bd388f1a65/lib/browsers/chrome.js#L145-L165

Upon disposing of the browser context, we check the response for success. It looks like Chrome 68 removed that response and no longer returns anything, so that's why you see that failure to dispose of the context, even though it actually does dispose of it.

The weird thing is we are closing the tab and disposing of the browser context so I would not expect to see all of those processes still open. It could be that since we `reject()` before `tab.browser.close()` is called, that might leave an extra process hanging around holding onto memory but I wouldn't think that would leave any tabs hanging around.

Either way, we'll push a fix for this and see if it fixes the issue. I'll post back here once that fix has been pushed to master.

**Comment by thoop** [comment]
I just pushed this change along with a few other small changes to master at commit https://github.com/prerender/prerender/commit/2e909d44e9bbb72e1d414d4bfc3d337ef3b01d3b

I'll publish a new npm version in the morning.

**Comment by thoop** [comment]
I just published `v5.4.4`. @diegojonio @dzydzany can you try that and let me know if you see an improvement or not?

**Comment by diegojonio** [comment]
Hi @thoop, thank you very much for your attention to this matter.

Anyway, I've updated my prerender cluster (less cpu) and now my deployment is way more stable. I'm not seeing that many tabs open and also I've been seen some Chrome restarts. Memory is now under control, using 400mb top with default memory cache config.

I haven't fetched your changes yet, so I still see the Chrome messages.So I'm not sure what actually could have fixed the memory issue.

 I'll do more tests using higher cache configuration for example: 100k pages with 1w cache and see the app behaves.

I'll fetch your changes after that.

Thank you!!!

<img width="1430" alt="screen shot 2018-08-08 at 10 27 31 am" src="https://user-images.githubusercontent.com/2515534/43854871-f7a48966-9af8-11e8-8e10-5146f0c36c40.png">

**Comment by thoop** [comment]
Thanks @diegojonio. You said less cpu, but do you mean you updated your prerender cluster to have more cpu?

Also, in that image you sent I can see 10 different server.js (Prerender) processes. If you are running all of those processes, it could be that each Chrome instance is listening on the same port and the overlap there could be causing issues leading to those orphaned tab issues over time. You should only need 1 Prerender server instance and Chrome will spread out the CPU load across all cores from the separate tabs.

So can you make sure you are just running a single Prerender server process per machine?

**Comment by dzydzany** [comment]
@thoop At my end, all is back to normal and expected. For some reason, I had to reboot complete VM where prerender is to free up resources. Thank you very much for a quick resolution.

**Comment by thoop** [comment]
I'm going to mark this as closed for now. Feel free to comment again if anyone runs into issues and we can reopen the issue if necessary.

**Comment by Darecjo** [comment]
Is this normal ? 

<img width="2534" height="1343" alt="Image" src="https://github.com/user-attachments/assets/89815ed8-a28e-42d8-91ce-e4d51353ce03" />
